# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Composer
                                 A QGIS plugin
 Creating color compositions from raster spatial data 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-19
        copyright            : (C) 2023 by Milosz Cygan
        email                : miloszcygan99@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Composer class from file Composer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .di_composer import Composer
    return Composer(iface)
